// 구글 시트에서 자동 변환된 초기 데이터 (프로젝트 진행현황 / 안나 / 찰스 / 피드백)
// 생성 스크립트: tools/transform (시트 원본 기준)
window.SEED_TASKS = [
 {
  "parentId": null,
  "task": "기존 상품 디벨롭+ 간략화 / 해외 회사 확인",
  "project": "상품 전략",
  "category": "기획/제안",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "기한:1달에 1번",
  "issue": "",
  "src": "master",
  "id": "tc194e9e1",
  "order": 0
 },
 {
  "parentId": null,
  "task": "집뷰 포럼 준비(콘텐츠 정리, 시연 플로우, 견적 확인)",
  "project": "집뷰 포럼(에스큐브 쇼룸)",
  "category": "마케팅",
  "assignee": "안나, 찰스",
  "priority": "",
  "start": "",
  "end": "2026-06-25",
  "status": "진행중",
  "doc": "LINK",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "ta206e0b0",
  "order": 1
 },
 {
  "parentId": null,
  "task": "올림플래닛 홈페이지 내 집뷰 내용 업데이트",
  "project": "집뷰",
  "category": "마케팅",
  "assignee": "안나",
  "priority": "",
  "start": "",
  "end": "2026-06-22",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t79351081",
  "order": 2
 },
 {
  "parentId": null,
  "task": "집뷰 소개서 - 체험 콘텐츠",
  "project": "집뷰",
  "category": "마케팅",
  "assignee": "안나, 찰스",
  "priority": "",
  "start": "",
  "end": "2026-06-17",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t6b7a5904",
  "order": 3
 },
 {
  "parentId": null,
  "task": "집뷰 홈페이지 도입사례 업데이트 (주2회)",
  "project": "집뷰",
  "category": "마케팅",
  "assignee": "안나",
  "priority": "",
  "start": "",
  "end": "2026-06-19",
  "status": "진행중",
  "doc": "",
  "progress": "개발팀에 전달",
  "issue": "",
  "src": "master",
  "id": "t7ef22c07",
  "order": 4
 },
 {
  "parentId": null,
  "task": "집뷰 뉴스레터 업데이트 (주2회)",
  "project": "집뷰",
  "category": "마케팅",
  "assignee": "안나",
  "priority": "",
  "start": "",
  "end": "2026-06-20",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "tc950f0f9",
  "order": 5
 },
 {
  "parentId": null,
  "task": "집뷰 리얼티 DB 연동하여 홍보 검토",
  "project": "집뷰 임장",
  "category": "마케팅",
  "assignee": "안나",
  "priority": "",
  "start": "",
  "end": "2026-06-10",
  "status": "대기중",
  "doc": "",
  "progress": "개발팀에 전달",
  "issue": "",
  "src": "master",
  "id": "ta9f8ad23",
  "order": 6
 },
 {
  "parentId": null,
  "task": "집뷰임장 홈페이지 추가 개선 검토",
  "project": "집뷰 임장",
  "category": "마케팅",
  "assignee": "안나",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t81d706f3",
  "order": 7
 },
 {
  "parentId": null,
  "task": "유튜브",
  "project": "집뷰",
  "category": "마케팅",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "기존은 포트폴리오, 홍보용 따로 개설",
  "issue": "",
  "src": "master",
  "id": "t25f664a9",
  "order": 8
 },
 {
  "parentId": null,
  "task": "협회, 지인 모임, 포럼, 박람회 리스트업",
  "project": "오프라인 모임",
  "category": "고객발굴",
  "assignee": "찰스, 안나",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t70cd74d4",
  "order": 9
 },
 {
  "parentId": null,
  "task": "분양 단지 수 확인, 매출 시물레이션",
  "project": "2026 매출 계획",
  "category": "기타 문서정리",
  "assignee": "찰스, 안나",
  "priority": "",
  "start": "2026-06-18",
  "end": "2026-06-26",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t9747f35a",
  "order": 10
 },
 {
  "parentId": null,
  "task": "pop 제작",
  "project": "소요한남",
  "category": "고객관리",
  "assignee": "안나",
  "priority": "",
  "start": "2026-06-18",
  "end": "2026-06-30",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "td2770d8c",
  "order": 11
 },
 {
  "parentId": null,
  "task": "진행 확인 및 고객관리",
  "project": "포레나힐스테이트 진주 이현",
  "category": "고객관리",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "2026-07-31",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t82ec9306",
  "order": 12
 },
 {
  "parentId": null,
  "task": "진행 확인 및 고객관리",
  "project": "동부 거제 상동",
  "category": "고객관리",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t06c4813f",
  "order": 13
 },
 {
  "parentId": null,
  "task": "진행 확인 및 고객관리",
  "project": "코오롱 전주 삼천주공",
  "category": "고객관리",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t432c7010",
  "order": 14
 },
 {
  "parentId": null,
  "task": "진행 확인 및 고객관리",
  "project": "벤틀리 레지던스 서울",
  "category": "고객관리",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t13ee73ad",
  "order": 15
 },
 {
  "parentId": null,
  "task": "진행 확인 및 고객관리",
  "project": "오산세교2 A-5BL 공공지원민간임대주택",
  "category": "고객관리",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "tc8bc141b",
  "order": 16
 },
 {
  "parentId": null,
  "task": "인코드와 함께 제안하는 건이며 견본주택 모델하우스내에 들어가는 영상 콘텐츠 제안",
  "project": "GS E&C 신규 모델하우스 제안",
  "category": "기획/제안",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "LINK",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "tc0e850be",
  "order": 17
 },
 {
  "parentId": null,
  "task": "플레이어 공간 내 측정 기능 제안",
  "project": "우미건설 시공 솔루션 제안",
  "category": "기획/제안",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "LINK",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "teba6a28d",
  "order": 18
 },
 {
  "parentId": null,
  "task": "매출, 매입 계약 정리",
  "project": "계약 정리",
  "category": "기타 문서정리",
  "assignee": "찰스",
  "priority": "",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "tbc409b62",
  "order": 19
 },
 {
  "parentId": null,
  "task": "신규 옵션몰 추가 개발 제안",
  "project": "GS 건설 옵션몰",
  "category": "기획/제안",
  "assignee": "찰스, 안나",
  "priority": "",
  "start": "2026-06-15",
  "end": "2026-06-15",
  "status": "완료",
  "doc": "LINK",
  "progress": "계약 완료",
  "issue": "",
  "src": "master",
  "id": "t898cb727",
  "order": 20
 },
 {
  "parentId": null,
  "task": "구인 홈페이지 업데이트/ 이력서 검토/ 면접",
  "project": "광고대행사 인재 발굴",
  "category": "기획/제안",
  "assignee": "찰스",
  "priority": "",
  "start": "2026-06-16",
  "end": "2026-06-18",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "src": "master",
  "id": "t34a5d18a",
  "order": 21
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "콘텐츠 정리",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t758185e9",
  "priority": "",
  "order": 22
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "콘텐츠 제작 확인",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-19",
  "status": "진행중",
  "doc": "",
  "progress": "사비나에게 전달",
  "issue": "",
  "id": "tc7a97693",
  "priority": "",
  "order": 23
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "DB 컨택",
  "category": "마케팅",
  "assignee": "안나",
  "start": "2026-06-08",
  "end": "2026-06-22",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t08ca2646",
  "priority": "",
  "order": 24
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "시연 플로우",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "",
  "progress": "대본 간략히 작성 필요",
  "issue": "",
  "id": "t13eac4bf",
  "priority": "",
  "order": 25
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "견적 확인",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "잭에게 견적 요청",
  "issue": "",
  "id": "t9baed33a",
  "priority": "",
  "order": 26
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "리허설",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-24",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t33184af9",
  "priority": "",
  "order": 27
 },
 {
  "parentId": "ta206e0b0",
  "src": "anna",
  "project": "집뷰 포럼_에스큐브 쇼룸",
  "task": "25일 운영",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-25",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t6ebb6ef8",
  "priority": "",
  "order": 28
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "집뷰 홈페이지 - 계룡건설",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-17",
  "status": "진행중",
  "doc": "",
  "progress": "개발팀 전달",
  "issue": "",
  "id": "t18b520ce",
  "priority": "",
  "order": 29
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "집뷰 홈페이지 - 송도 G5",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-19",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t6ba2b558",
  "priority": "",
  "order": 30
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "집뷰 뉴스레터 - 계룡건설",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-20",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tcf5c5352",
  "priority": "",
  "order": 31
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "집뷰 뉴스레터 - 송도 G5",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-21",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tb5f78692",
  "priority": "",
  "order": 32
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "도입사례 텍스트 걸리게 개발 확인",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-22",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t8f99b4ec",
  "priority": "",
  "order": 33
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "기사 확인",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "",
  "progress": "기한:매일",
  "issue": "",
  "id": "t466ac530",
  "priority": "",
  "order": 34
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홈페이지",
  "task": "올림플래닛 홈페이지 내 집뷰 내용 업데이트",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t2154c120",
  "priority": "",
  "order": 35
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_소개서",
  "task": "체험 마케팅으로 정리",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-19",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "td7da621e",
  "priority": "",
  "order": 36
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홍보",
  "task": "뉴스레터 매주 보낼 키워드 정하기",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t60a3184a",
  "priority": "",
  "order": 37
 },
 {
  "parentId": "t79351081",
  "src": "anna",
  "project": "집뷰_홍보",
  "task": "뉴스레터 보낼 리스트업하기",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "td83301aa",
  "priority": "",
  "order": 38
 },
 {
  "parentId": "ta9f8ad23",
  "src": "anna",
  "project": "집뷰 임장",
  "task": "DB 연결",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "개발팀 전달",
  "issue": "",
  "id": "tdad77058",
  "priority": "",
  "order": 39
 },
 {
  "parentId": "ta9f8ad23",
  "src": "anna",
  "project": "집뷰 임장",
  "task": "유저 연락",
  "category": "마케팅",
  "assignee": "안나",
  "start": "",
  "end": "",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t9f458170",
  "priority": "",
  "order": 40
 },
 {
  "parentId": "td2770d8c",
  "src": "anna",
  "project": "소요한남",
  "task": "pop 팝업 달기",
  "category": "고객관리",
  "assignee": "안나",
  "start": "",
  "end": "2026-06-30",
  "status": "대기중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t7a5f8e44",
  "priority": "",
  "order": 41
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "GS 재견적 전달",
  "task": "유지보수 포함하여 견적 전달 , 네고 >> 계약서 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-11",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "te6cf6f01",
  "priority": "",
  "order": 42
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "주봉, 에스큐브랩 시연 준비",
  "task": "필요 자료 요청, 제원/금액 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t1277452e",
  "priority": "",
  "order": 43
 },
 {
  "parentId": null,
  "task": "모닝스타애드",
  "project": "모닝스타애드",
  "category": "고객관리",
  "assignee": "찰스",
  "status": "진행중",
  "src": "auto-parent",
  "id": "t4fe644b0",
  "priority": "",
  "start": "",
  "end": "",
  "doc": "",
  "progress": "",
  "issue": "",
  "order": 44
 },
 {
  "parentId": "t4fe644b0",
  "src": "charles",
  "project": "모닝스타애드",
  "task": "업데이트 임장 광고 전달 및 컨펌",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-10",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t92ab5849",
  "priority": "",
  "order": 45
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "계약서 작성, 품의서",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "거래처:에스큐브 · 담당:김우창 이사",
  "issue": "",
  "id": "tdc1044b2",
  "priority": "",
  "order": 46
 },
 {
  "parentId": null,
  "task": "거제 상동",
  "project": "거제 상동",
  "category": "고객관리",
  "assignee": "찰스",
  "status": "진행중",
  "src": "auto-parent",
  "id": "t51d3cb53",
  "priority": "",
  "start": "",
  "end": "",
  "doc": "",
  "progress": "",
  "issue": "",
  "order": 47
 },
 {
  "parentId": "t51d3cb53",
  "src": "charles",
  "project": "거제 상동",
  "task": "현장 소장 확인하여 인터넷 연결 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t63c854ad",
  "priority": "",
  "order": 48
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "일정표, 기획서 작성",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tcfd7fd84",
  "priority": "",
  "order": 49
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "레이존 계약품의 기안",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tf564c71d",
  "priority": "",
  "order": 50
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "디오씨앤디 지급요청서 기안",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tfedf50af",
  "priority": "",
  "order": 51
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "선금 일정 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "담당:정성용 과장",
  "issue": "",
  "id": "ta0a49b1d",
  "priority": "",
  "order": 52
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "네오플랜 평면 외주",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-10",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t1075ee51",
  "priority": "",
  "order": 53
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "진행 일정, 기획안 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "ta8329bc6",
  "priority": "",
  "order": 54
 },
 {
  "parentId": "t13ee73ad",
  "src": "charles",
  "project": "벤틀리 레지던스 서울",
  "task": "어메니티 진행 공간 확정   >> 4명이 체험해도 될 정도의 공간으로 제안 드리기로 함",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:루시아홀딩스 · 담당:이창훈 전무",
  "issue": "",
  "id": "tff42da43",
  "priority": "",
  "order": 55
 },
 {
  "parentId": "t13ee73ad",
  "src": "charles",
  "project": "벤틀리 레지던스 서울",
  "task": "어메니티 진행 및 오큘러스 체험 개발 견적 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:레이존 · 담당:구형근 대표",
  "issue": "",
  "id": "t8ed08ff0",
  "priority": "",
  "order": 56
 },
 {
  "parentId": "t13ee73ad",
  "src": "charles",
  "project": "벤틀리 레지던스 서울",
  "task": "벤틀리 필요자료 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "담당:제스퍼",
  "issue": "",
  "id": "t06e11c5a",
  "priority": "",
  "order": 57
 },
 {
  "parentId": "t13ee73ad",
  "src": "charles",
  "project": "벤틀리 레지던스 서울",
  "task": "벤틀리 진행사항 최종 정리 , 어메니티 정리, 벤틀리 영상",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "담당:찰스",
  "issue": "",
  "id": "t205edfcd",
  "priority": "",
  "order": 58
 },
 {
  "parentId": "t13ee73ad",
  "src": "charles",
  "project": "벤틀리 레지던스 서울",
  "task": "진행률확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t219a3b59",
  "priority": "",
  "order": 59
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "매입 외주",
  "task": "외주 취합 및 지급요청서 상신, 외주 추가 상신(주봉 등)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "ta3f74bdf",
  "priority": "",
  "order": 60
 },
 {
  "parentId": "tc8bc141b",
  "src": "charles",
  "project": "오산세교2",
  "task": "일정표, 기획서 작성",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t2b02e8c3",
  "priority": "",
  "order": 61
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "한빛커뮤니케이션 제안",
  "task": "추가 입찰 제안하는 사업지의 견적 확인(단독주택 사이트)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:한빛커뮤니케이션 · 담당:임대섭 전무",
  "issue": "",
  "id": "t6f5dd224",
  "priority": "",
  "order": 62
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "리얼티 추가 단지  선정",
  "task": "리얼티 추가 단지  선정",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "te3540f54",
  "priority": "",
  "order": 63
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "한양건설",
  "task": "화곡동 사업지 임장에 추가",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tea23eeaa",
  "priority": "",
  "order": 64
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "일경험",
  "task": "사이니지 합성 영상 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "담당:버디",
  "issue": "",
  "id": "t2106cf98",
  "priority": "",
  "order": 65
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "베어 추가 외주 진행 건",
  "task": "베어 추가 외주 진행 건",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t61907dee",
  "priority": "",
  "order": 66
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "송도 G5 기사 확인",
  "task": "비용 부분 제외하고 다시 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "거래처:포스코 · 담당:서종희 차장",
  "issue": "",
  "id": "t31732c03",
  "priority": "",
  "order": 67
 },
 {
  "parentId": "t51d3cb53",
  "src": "charles",
  "project": "거제 상동",
  "task": "CG 확인사항 검토",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-17",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tbfb9268d",
  "priority": "",
  "order": 68
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "알렉스 요청 영상",
  "task": "외주 확인(베어확인)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t36174f81",
  "priority": "",
  "order": 69
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "해운대구 재송동 공동주택 견적 작성",
  "task": "해운대구 재송동 공동주택 견적 작성",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-16",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "te3be702e",
  "priority": "",
  "order": 70
 },
 {
  "parentId": "tc8bc141b",
  "src": "charles",
  "project": "오산세교2",
  "task": "외주 세팅(238아뜰리에)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t3c63122f",
  "priority": "",
  "order": 71
 },
 {
  "parentId": "tc8bc141b",
  "src": "charles",
  "project": "오산세교2",
  "task": "최종 도면인지 확인, 층고 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-12",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t2d2ecaa3",
  "priority": "",
  "order": 72
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "포럼 초대 인원 확인",
  "task": "포럼 초대 인원 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-12",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t93e78494",
  "priority": "",
  "order": 73
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "일정표, 기획서 작성",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tda6aecd1",
  "priority": "",
  "order": 74
 },
 {
  "parentId": "tc8bc141b",
  "src": "charles",
  "project": "오산세교2",
  "task": "dp 제안서 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:우미건설 · 담당:나승훈 과장",
  "issue": "",
  "id": "t4b1d704b",
  "priority": "",
  "order": 75
 },
 {
  "parentId": "t4fe644b0",
  "src": "charles",
  "project": "모닝스타애드",
  "task": "2~4월 매입 지급요청서",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "tf27c1411",
  "priority": "",
  "order": 76
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "외주 노소정, 정승환 급여 정산일 확인",
  "task": "외주 노소정, 정승환 급여 정산일 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-09",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t80b399ae",
  "priority": "",
  "order": 77
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "에스큐브랩 일정 확인, 설치 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-08",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t965c318f",
  "priority": "",
  "order": 78
 },
 {
  "parentId": "tc8bc141b",
  "src": "charles",
  "project": "오산세교2",
  "task": "계약확인, dp 제안서 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:우미건설 · 담당:나승훈 과장",
  "issue": "",
  "id": "tda4c396e",
  "priority": "",
  "order": 79
 },
 {
  "parentId": null,
  "task": "더샵 송도 G5",
  "project": "더샵 송도 G5",
  "category": "고객관리",
  "assignee": "찰스",
  "status": "진행중",
  "src": "auto-parent",
  "id": "t754d3e0e",
  "priority": "",
  "start": "",
  "end": "",
  "doc": "",
  "progress": "",
  "issue": "",
  "order": 80
 },
 {
  "parentId": "t754d3e0e",
  "src": "charles",
  "project": "더샵 송도 G5",
  "task": "최종 완료 및 웹버전 오픈 요청, 기사 요청",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:포스코 · 담당:서종희 부장",
  "issue": "",
  "id": "t422c9439",
  "priority": "",
  "order": 81
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "LCD 견적 확인 후 코오롱 정성용 과장에게 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-08",
  "status": "완료",
  "doc": "",
  "progress": "거래처:에스큐브랩 · 담당:김우창 이사 · 기존 견적에 포함으로 정리",
  "issue": "",
  "id": "t75617010",
  "priority": "",
  "order": 82
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "하드웨어 설치 견적 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-08",
  "status": "완료",
  "doc": "",
  "progress": "거래처:에스큐브랩 · 담당:김우창 이사",
  "issue": "",
  "id": "t702f9d83",
  "priority": "",
  "order": 83
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "오티에르 반포",
  "task": "잔금 확인 >> 5월 31일 세금계산서 발행",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "",
  "status": "진행중",
  "doc": "",
  "progress": "거래처:넥스미디어 · 담당:백동현 이사",
  "issue": "",
  "id": "t159054f2",
  "priority": "",
  "order": 84
 },
 {
  "parentId": null,
  "task": "전라남도 함안",
  "project": "전라남도 함안",
  "category": "고객관리",
  "assignee": "찰스",
  "status": "진행중",
  "src": "auto-parent",
  "id": "t59a2d6ae",
  "priority": "",
  "start": "",
  "end": "",
  "doc": "",
  "progress": "",
  "issue": "",
  "order": 85
 },
 {
  "parentId": "t59a2d6ae",
  "src": "charles",
  "project": "전라남도 함안",
  "task": "투어 영상 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-05",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t22819783",
  "priority": "",
  "order": 86
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "올리브영 티커(2월~3월)",
  "task": "세금계산서 발행",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-04",
  "status": "완료",
  "doc": "",
  "progress": "거래처:에스큐브랩",
  "issue": "",
  "id": "t894be7d7",
  "priority": "",
  "order": 87
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "일정 픽스 및 계약 품의 / 차량 렌탈   >> 품의 올리고 사유 적기(평면 > 공사비로)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-01",
  "status": "완료",
  "doc": "",
  "progress": "담당:김경호 대표",
  "issue": "",
  "id": "t14ee41da",
  "priority": "",
  "order": 88
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "타공 사이즈 및 디테일 다시 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-05",
  "status": "완료",
  "doc": "",
  "progress": "거래처:에스큐브랩 · 담당:김우창 이사",
  "issue": "",
  "id": "tbf8b4bce",
  "priority": "",
  "order": 89
 },
 {
  "parentId": "t06c4813f",
  "src": "charles",
  "project": "동부 거제 상동2지구",
  "task": "계약서 날인본 요청 / 2차 추가건 입금 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-05",
  "status": "완료",
  "doc": "",
  "progress": "거래처:한국토지신탁 · 담당:전현호 차장",
  "issue": "",
  "id": "t4c94be31",
  "priority": "",
  "order": 90
 },
 {
  "parentId": "t13ee73ad",
  "src": "charles",
  "project": "벤틀리 레지던스 서울",
  "task": "수정 이미지 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-05",
  "status": "완료",
  "doc": "",
  "progress": "거래처:루시아홀딩스 · 담당:이창훈 전무",
  "issue": "",
  "id": "te22b5ce0",
  "priority": "",
  "order": 91
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "개인비용 상신",
  "task": "개인비용 상신",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-03",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t55d8e91c",
  "priority": "",
  "order": 92
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "블라시오 요청 작성하기",
  "task": "블라시오 요청 작성하기",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-03",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "ta89ad4eb",
  "priority": "",
  "order": 93
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "동문 장승배기",
  "task": "잔금 세금계산서 발행",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-01",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t0f5db141",
  "priority": "",
  "order": 94
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "GS 옵션몰 제안 및 견적 전달",
  "task": "GS 옵션몰 제안 및 견적 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-06-02",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "t7c1e3ac2",
  "priority": "",
  "order": 95
 },
 {
  "parentId": "t4fe644b0",
  "src": "charles",
  "project": "모닝스타애드",
  "task": "- 3/25 : 4월 미디어아트 영상 샘플 전달\n- 3/31 : 세금계산서 발행 (3개월치)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-29",
  "status": "완료",
  "doc": "",
  "progress": "거래처:Charles",
  "issue": "",
  "id": "ta9f365b0",
  "priority": "",
  "order": 96
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "르엘어퍼하우스",
  "task": "잔금 세금계산서 발행",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-29",
  "status": "완료",
  "doc": "",
  "progress": "거래처:인코드",
  "issue": "",
  "id": "te0f74c7c",
  "priority": "",
  "order": 97
 },
 {
  "parentId": "tc8bc141b",
  "src": "charles",
  "project": "오산세교2",
  "task": "계약 서류 전달(주주명부 날인본, 법인 등기부등본,사업자등록증)",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-29",
  "status": "완료",
  "doc": "",
  "progress": "거래처:우미건설 · 담당:나승훈 과장",
  "issue": "",
  "id": "tedf953a0",
  "priority": "",
  "order": 98
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "더샵 오산역아크시티",
  "task": "계약서 전달 >> 홀딩",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-29",
  "status": "완료",
  "doc": "",
  "progress": "거래처:포스코(디자인호인)",
  "issue": "",
  "id": "t423cc717",
  "priority": "",
  "order": 99
 },
 {
  "parentId": "t59a2d6ae",
  "src": "charles",
  "project": "전라남도",
  "task": "잔금 세금계산서 발행",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-29",
  "status": "완료",
  "doc": "",
  "progress": "거래처:더시프트 · 담당:송지유 부장",
  "issue": "",
  "id": "t7267d866",
  "priority": "",
  "order": 100
 },
 {
  "parentId": null,
  "task": "한화 상인천",
  "project": "한화 상인천",
  "category": "고객관리",
  "assignee": "찰스",
  "status": "진행중",
  "src": "auto-parent",
  "id": "t4d91ee1b",
  "priority": "",
  "start": "",
  "end": "",
  "doc": "",
  "progress": "",
  "issue": "",
  "order": 101
 },
 {
  "parentId": "t4d91ee1b",
  "src": "charles",
  "project": "한화 상인천",
  "task": "복구 공사",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-27",
  "status": "완료",
  "doc": "",
  "progress": "거래처:한화건설 · 담당:김진국 대리",
  "issue": "",
  "id": "t346c9351",
  "priority": "",
  "order": 102
 },
 {
  "parentId": "t432c7010",
  "src": "charles",
  "project": "코오롱 전주삼천주공",
  "task": "LCD 타공 사이즈 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:비오 · 담당:정송이 부장,성기훈 주임",
  "issue": "",
  "id": "td666728c",
  "priority": "",
  "order": 103
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "네오오토",
  "task": "추가 진행 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:네오오토 · 담당:김용주",
  "issue": "",
  "id": "td0a23ca9",
  "priority": "",
  "order": 104
 },
 {
  "parentId": "t4d91ee1b",
  "src": "charles",
  "project": "한화 상인천",
  "task": "철거& 복구 견적 및 일정 픽스 / 계약 품의",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:한화건설 · 담당:김진국 대리",
  "issue": "",
  "id": "t70f1114d",
  "priority": "",
  "order": 105
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "엘리프 세종 스마트시티",
  "task": "비용 지급 일정 확인 >>",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "담당:임대섭 전무",
  "issue": "",
  "id": "taeb5740c",
  "priority": "",
  "order": 106
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "모닝스타 미디어아트",
  "task": "6월 미디어아트 전달 >> 무궁화 좀 더 화사하게 처리",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:모닝스타 · 담당:박주현 대표",
  "issue": "",
  "id": "t4dd15995",
  "priority": "",
  "order": 107
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "SH",
  "task": "강경모 외주 품의, 카톡방 개설",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "",
  "issue": "",
  "id": "ta95b396c",
  "priority": "",
  "order": 108
 },
 {
  "parentId": "t59a2d6ae",
  "src": "charles",
  "project": "전라남도 함안",
  "task": "최종본 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:더시프트 · 담당:송지유 부장",
  "issue": "",
  "id": "tba156764",
  "priority": "",
  "order": 109
 },
 {
  "parentId": "t754d3e0e",
  "src": "charles",
  "project": "더샵 송도 G5",
  "task": "수정 반영",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:예인 · 담당:박나혜 프로",
  "issue": "",
  "id": "t70aef14c",
  "priority": "",
  "order": 110
 },
 {
  "parentId": "t82ec9306",
  "src": "charles",
  "project": "포레나힐스테이트 진주 이현",
  "task": "옵션 평면 완료 전달",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "거래처:네오플랜 · 담당:최재현 팀장",
  "issue": "",
  "id": "tc85b68c5",
  "priority": "",
  "order": 111
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "올리브영 티커(홍대입구 익스클루시브존)",
  "task": "진행건 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-26",
  "status": "완료",
  "doc": "",
  "progress": "담당:베어",
  "issue": "",
  "id": "tfb78887d",
  "priority": "",
  "order": 112
 },
 {
  "parentId": null,
  "src": "charles",
  "project": "캠페인 인계서 작성",
  "task": "캠페인 인계서 작성",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-22",
  "status": "완료",
  "doc": "",
  "progress": "담당:에나",
  "issue": "",
  "id": "t044743ed",
  "priority": "",
  "order": 113
 },
 {
  "parentId": "t754d3e0e",
  "src": "charles",
  "project": "더샵 송도 G5",
  "task": "잔금 세금계산서 발행 확인 >> 22일 세금계산서 발행 확정",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-22",
  "status": "완료",
  "doc": "",
  "progress": "거래처:포애드원 · 담당:채지원 팀장",
  "issue": "",
  "id": "t23d48903",
  "priority": "",
  "order": 114
 },
 {
  "parentId": "t06c4813f",
  "src": "charles",
  "project": "동부 거제 상동2지구",
  "task": "2차 추가건 잔금 요청 / 세금계산서 발행 요청",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-22",
  "status": "완료",
  "doc": "",
  "progress": "거래처:한국토지신탁 · 담당:전현호 차장",
  "issue": "",
  "id": "t40f752f8",
  "priority": "",
  "order": 115
 },
 {
  "parentId": "t06c4813f",
  "src": "charles",
  "project": "동부 거제 상동2지구",
  "task": "이미지, 영상 컨펌 확인",
  "category": "고객관리",
  "assignee": "찰스",
  "start": "",
  "end": "2026-05-22",
  "status": "완료",
  "doc": "",
  "progress": "거래처:디자인데이 · 담당:이동환 과장",
  "issue": "",
  "id": "ta4970919",
  "priority": "",
  "order": 116
 },
 {
  "parentId": null,
  "task": "집뷰 서비스 피드백",
  "project": "집뷰 서비스 피드백",
  "category": "피드백",
  "status": "진행중",
  "src": "feed-parent",
  "id": "t6e958d9f",
  "assignee": "",
  "priority": "",
  "start": "",
  "end": "",
  "doc": "",
  "progress": "",
  "issue": "",
  "order": 117
 },
 {
  "parentId": "t6e958d9f",
  "task": "동문 천안삼룡 피드백",
  "project": "집뷰 서비스 피드백",
  "category": "피드백",
  "assignee": "찰스",
  "start": "2026-06-11",
  "status": "진행중",
  "progress": "거래처:알파고(계약클라이언트) · 담당:서덕조 대표 · 피드백:웹버전 고화질 전환 시 불러오는 시간이 길다는 의견 (투어링크) · 대응:원본 파일을 불러오는 방식이다 보니 로딩 시간이 긴 부분에 대해서 설명",
  "issue": "개선:로딩중 디자인 변경(게이지가 차는 방향), 고화질 압축 % 조정",
  "src": "feed",
  "id": "t9bc6741a",
  "priority": "",
  "end": "",
  "doc": "",
  "order": 118
 }
];
